### ISSUE TITLE
support dbt audit_helper >= 0.3.0 with dbt >=0.19.2

### ISSUE THREAD

**Issue by jups23** [tglunde/dbt-exasol#13]
### Error description
It seems that dbt-exasol is not compatible with audit_helper 0.3.0 after an update from dbt 0.18.2 to 0.19.2.

While compiling my project I get the following error: 

```
Running with dbt=0.19.2
Encountered an error:
Compilation Error
  In dispatch: No macro named 'get_columns_in_relation_sql' found
      Searched for: 'audit_helper.exasol__get_columns_in_relation_sql', 'audit_helper.default__get_columns_in_relation_sql'
```
My packages:
```
packages:
  - package: fishtown-analytics/dbt_utils
    version: 0.6.6
  - package: fishtown-analytics/audit_helper
    version: 0.3.0
```

Even without any invocation of any macro of `audit_helper` running any `dbt` command leads to the crash described above.
I could resolve this run-time error only by deleting the `audit_helper` from the ` packages.yml`.

The reason is [described in this thread](https://getdbt.slack.com/archives/CU4MRJ7QB/p1626101338074600?thread_ts=1626093664.073500&cid=CU4MRJ7QB): dbt v0.19 statically analyzes macro dependencies to optimize compilation time.

### Proposed Solution
Implement the missing macro in the to-be-created shim package for Exasol. I haven't seen it taking off yet. Therefore, I wanted to document my solution.

I oriented myself around [the code for the databases supported by dbt](https://github.com/dbt-labs/dbt-audit-helper/blob/f0f0e4a504b15556ed96d97d88a8df38d7a551e5/macros/compare_relation_columns.sql#L30)

macros/get_columns_in_relation.sql
``` 
{% macro exasol__get_columns_in_relation_sql(relation) %}
select
  column_ordinal_position as ordinal_position,
  column_name,
  column_type as data_type,
  column_maxsize as character_maximum_length,
  column_num_prec as numeric_precision,
  column_num_scale as numeric_scale

from exa_all_columns
where
  lower(column_schema) = lower('{{ relation.schema }}')
  and lower(column_table) = lower('{{ relation.identifier }}')
  
{% endmacro %}
``` 

in dbt_project.yml add:
```
# Variables
vars:
  dbt_utils_dispatch_list:
    - '<project_name>' # this is for dateadd, surrogate_key, and current_timestamp as discussed in https://github.com/tglunde/dbt-exasol/issues/9
  audit_helper_dispatch_list:
    - '<project_name>' # this is for get_columns_in_relation_sql

```

**Comment by tglunde** [comment]
Hi we created a shim: git@github.com:tglunde/exasol-utils.git

Could you give it a try?

**Comment by jups23** [comment]
fantastic!
